// Dos copias de historial de ejemplo, deliberadamente separadas: los
// íconos difieren entre escritorio ("ruler-2") y móvil ("ruler").
// No fusionar — cada vista usa su propia copia.
export const HISTORIAL_DESKTOP = [
  {
    id: 1,
    fecha: "Hoy 10:32",
    modulo: "Cómputos",
    descripcion: "Columna 0.30×0.30 m — ×12",
    proyecto: "Edif. Residencial",
    resultado: "3.24 m³",
    moduloKey: "computos",
    badgeBg: "#E8F8EF",
    badgeColor: "#166534",
    icon: "ruler-2",
  },
  {
    id: 2,
    fecha: "Ayer 16:15",
    modulo: "Concreto",
    descripcion: "Dosificación f'c 210 — 3 m³",
    proyecto: "Edif. Residencial",
    resultado: "21 sacos",
    moduloKey: "concreto",
    badgeBg: "#FEF3E8",
    badgeColor: "#9A3412",
    icon: "building",
  },
  {
    id: 3,
    fecha: "Ayer 14:08",
    modulo: "Estimación",
    descripcion: "Pintura interior — 120 m²",
    proyecto: "Edif. Residencial",
    resultado: "8 galones",
    moduloKey: "estimacion",
    badgeBg: "#EFF4FF",
    badgeColor: "#1D4ED8",
    icon: "calculator",
  },
  {
    id: 4,
    fecha: "Hace 3 días",
    modulo: "Cómputos",
    descripcion: "Viga 0.25×0.50 m — ×8",
    proyecto: "C. Comercial",
    resultado: "8.0 m³",
    moduloKey: "computos",
    badgeBg: "#E8F8EF",
    badgeColor: "#166534",
    icon: "ruler-2",
  },
  {
    id: 5,
    fecha: "Hace 5 días",
    modulo: "Concreto",
    descripcion: "Dosificación f'c 180 — 5 m³",
    proyecto: "Colegio Municipal",
    resultado: "30 sacos",
    moduloKey: "concreto",
    badgeBg: "#FEF3E8",
    badgeColor: "#9A3412",
    icon: "building",
  },
  {
    id: 6,
    fecha: "Hace 1 sem",
    modulo: "Estimación",
    descripcion: "Cerámica piso — 85 m²",
    proyecto: "Vivienda Bogotá",
    resultado: "93.5 m²",
    moduloKey: "estimacion",
    badgeBg: "#EFF4FF",
    badgeColor: "#1D4ED8",
    icon: "calculator",
  },
];

export const HISTORIAL_MOBILE = [
  {
    id: 1,
    fecha: "Hoy 10:32",
    modulo: "Cómputos",
    descripcion: "Columna 0.30×0.30 m — ×12",
    proyecto: "Edif. Residencial",
    resultado: "3.24 m³",
    moduloKey: "computos",
    badgeBg: "#E8F8EF",
    badgeColor: "#166534",
    icon: "ruler",
  },
  {
    id: 2,
    fecha: "Ayer 16:15",
    modulo: "Concreto",
    descripcion: "Dosificación f'c 210 — 3 m³",
    proyecto: "Edif. Residencial",
    resultado: "21 sacos",
    moduloKey: "concreto",
    badgeBg: "#FEF3E8",
    badgeColor: "#9A3412",
    icon: "building",
  },
  {
    id: 3,
    fecha: "Ayer 14:08",
    modulo: "Estimación",
    descripcion: "Pintura interior — 120 m²",
    proyecto: "Edif. Residencial",
    resultado: "8 galones",
    moduloKey: "estimacion",
    badgeBg: "#EFF4FF",
    badgeColor: "#1D4ED8",
    icon: "calculator",
  },
  {
    id: 4,
    fecha: "Hace 3 días",
    modulo: "Cómputos",
    descripcion: "Viga 0.25×0.50 m — ×8",
    proyecto: "C. Comercial",
    resultado: "8.0 m³",
    moduloKey: "computos",
    badgeBg: "#E8F8EF",
    badgeColor: "#166534",
    icon: "ruler",
  },
  {
    id: 5,
    fecha: "Hace 5 días",
    modulo: "Concreto",
    descripcion: "Dosificación f'c 180 — 5 m³",
    proyecto: "Colegio Municipal",
    resultado: "30 sacos",
    moduloKey: "concreto",
    badgeBg: "#FEF3E8",
    badgeColor: "#9A3412",
    icon: "building",
  },
  {
    id: 6,
    fecha: "Hace 1 sem",
    modulo: "Estimación",
    descripcion: "Cerámica piso — 85 m²",
    proyecto: "Vivienda Bogotá",
    resultado: "93.5 m²",
    moduloKey: "estimacion",
    badgeBg: "#EFF4FF",
    badgeColor: "#1D4ED8",
    icon: "calculator",
  },
];
