export const NORMAS_DOCUMENTS = [
  {
    id: "covenin-1753-2006",
    code: "COVENIN 1753-2006",
    title: "Proyecto y construcción de obras de concreto estructural",
    type: "Concreto estructural",
    source: "Covenin 1753-2006 Proyecto Construccion Obras Concreto Estructural.pdf",
    summary: "Documento base para proyectos y construcción en concreto estructural.",
    tags: ["Diseño", "Concreto", "Estructuras"],
    tone: "blue",
  },
  {
    id: "covenin-1756-2018",
    code: "COVENIN 1756-2018",
    title: "Norma incluida en la biblioteca",
    type: "Complementaria",
    source: "COVENIN 1756-2018.pdf",
    summary: "Referencia técnica incorporada a la biblioteca del proyecto.",
    tags: ["Norma", "Referencia", "Incluida"],
    tone: "green",
  },
  {
    id: "covenin-2002-88",
    code: "COVENIN 2002-88",
    title: "Acciones mínimas",
    type: "Acciones y cargas",
    source: "COVENIN 2002-88 acciones minimas.pdf",
    summary: "Base normativa para acciones mínimas aplicables al análisis.",
    tags: ["Cargas", "Acciones", "Análisis"],
    tone: "orange",
  },
  {
    id: "diseno-estructural-concreto-armado",
    code: "Manual de apoyo",
    title: "Diseño estructural en concreto armado",
    type: "Guía técnica",
    source: "DISEÑO_ESTRUCTURAL_EN_CONCRETO_ARMADO.pdf",
    summary: "Material de consulta para reforzar criterios de diseño y cálculo.",
    tags: ["Guía", "Diseño", "Apoyo"],
    tone: "purple",
  },
  {
    id: "covenin-1618-1998",
    code: "COVENIN 1618-1998",
    title: "Estructuras de acero",
    type: "Acero estructural",
    source: "Norma COVENIN 1618-1998 ESTRUCTURAS DE ACERO.pdf.crdownload.pdf",
    summary: "Norma de referencia para estructuras de acero incorporada en la biblioteca.",
    tags: ["Acero", "Estructuras", "Referencia"],
    tone: "blue",
  },
];

export const NORMAS_CATEGORIES = [
  { key: "todas", label: "Todas" },
  { key: "concreto estructural", label: "Concreto" },
  { key: "acciones y cargas", label: "Acciones" },
  { key: "acero estructural", label: "Acero" },
  { key: "guía técnica", label: "Guías" },
  { key: "complementaria", label: "Complementarias" },
];
